modbus_controller:
  - id: nt48b20
    address: 20
    modbus_id: pomiary_modbus
    setup_priority: -10
    update_interval: 10s

sensor:

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_1
    name: "NTC 1"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 0
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_2
    name: "NTC 2"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 1
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_3
    name: "NTC 3"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 2
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_4
    name: "NTC 4"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 3
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_5
    name: "NTC 5"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 4
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_6
    name: "NTC 6"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 5
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_7
    name: "NTC 7"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 6
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_8
    name: "NTC 8"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 7
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_9
    name: "NTC 9"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 8
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_10
    name: "NTC 10"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 9
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_11
    name: "NTC 11"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 10
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_12
    name: "NTC 12"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 11
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_13
    name: "NTC 13"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 12
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_14
    name: "NTC 14"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 13
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_15
    name: "NTC 15"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 14
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: nt48b20
    id: ntc_16
    name: "NTC 16"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 15
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
