modbus_controller:
  - id: pt100x8
    address: 13
    modbus_id: pomiary_modbus
    setup_priority: -10
    update_interval: 60s

sensor:

  - platform: modbus_controller #Ua
    modbus_controller_id: pt100x8
    id: pt100_testowa_1
    name: "Temperatura testowa 1"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 0x0
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: pt100x8
    id: pt100_testowa_2
    name: "Temperatura testowa 2"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 0x1
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: pt100x8
    id: pt100_testowa_3
    name: "Temperatura testowa 3"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 0x2
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: pt100x8
    id: pt100_testowa_4
    name: "Temperatura testowa 4"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 0x3
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: pt100x8
    id: pt100_testowa_5
    name: "Temperatura testowa 5"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 0x4
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1    
