modbus_controller:    
  - id: ebyte
    address: 12
    modbus_id: pomiary_modbus 
    setup_priority: -10
    update_interval: 60s

sensor:
  - platform: modbus_controller #Ua
    modbus_controller_id: ebyte
    id: ebyte_pt100_1
    name: "Temperatura ebyte PT100 1"
    state_class: measurement
    device_class: temperature
    unit_of_measurement: "째C"
    icon: "mdi:water-percent"
    register_type: read
    address: 400
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
     
  - platform: modbus_controller #Ua
    modbus_controller_id: ebyte
    id: ebyte_PT100_2
    name: "Temperatura ebyte PT100 2"
    state_class: measurement
    device_class: temperature
    unit_of_measurement: "째C"
    icon: "mdi:water-percent"
    register_type: read
    address: 401
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: ebyte
    id: ebyte_PT100_3
    name: "Temperatura ebyte PT100 3"
    state_class: measurement
    device_class: temperature
    unit_of_measurement: "째C"
    icon: "mdi:water-percent"
    register_type: read
    address: 402
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller #Ua
    modbus_controller_id: ebyte
    id: ebyte_PT100_4
    name: "Temperatura ebyte PT100 4"
    state_class: measurement
    device_class: temperature
    unit_of_measurement: "째C"
    icon: "mdi:water-percent"
    register_type: read
    address: 403
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
