modbus_controller: 
  - id: pt100
    address: 1
    modbus_id: pomiary_modbus
    setup_priority: -10
    update_interval: 60s

sensor:
  - platform: modbus_controller #Ua
    modbus_controller_id: pt100
    id: pt100_rozdzielnia
    name: "Temperatura rozdzielnia"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 0x0
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
