modbus_controller:
  - id: pt100_8
    address: 13
    modbus_id: pomiary_modbus
    setup_priority: -10
    update_interval: 5s

sensor:
  - platform: modbus_controller #Ua
    modbus_controller_id: pt100_8
    id: pt100_testowa
    name: "Temperatura testowa"
    state_class: measurement
    device_class: temperature
    register_type: holding
    address: 0x0
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
